### ISSUE TITLE
I can't push my branch

### ISSUE THREAD

**Issue by spencerk80** [RaiderSoft/DGGRID#2]
Steps taken:

git clone (the repo)
git checkout -b ClipPoly
git push origin ClipPoly

Expected:

success

Actual result:

remote: Permission to RaiderSoft/DGGRID.git denied to spencerk80.
fatal: unable to access 'https://github.com/RaiderSoft/DGGRID.git/': The requested URL returned error: 403

**Comment by EspressoDan** [comment]
I added you as a collaborator. Try it again

**Comment by spencerk80** [comment]
Resolved, thank you
