### ISSUE TITLE
ClipPoly is a submodule

### ISSUE THREAD

**Issue by spencerk80** [RaiderSoft/DGGRID#4]
I messed with it a bit, but I'm having issues stripping its status as a sub-module. 

Tried:

git add clippoly/*
FATAL: Pathspec 'clippoly/case1' is in submodule 'src/lib/clippoly'

git submodule deinit clippoly
No submodule mapping found in .gitmodules for path 'src/lib/clippoly'

**Comment by EspressoDan** [comment]
What is the output of your `git status`?
